<?php
$pageTitle='Settings';
require_once __DIR__.'/../includes/header.php';
require_once __DIR__.'/../includes/sidebar.php';
requireRole(['owner','manager']);
$db=getDB();$club=$_SESSION['club_id'];$tab=$_GET['tab']??'club';
if($_SERVER['REQUEST_METHOD']==='POST'){
    verifyCsrf();$action=$_POST['action']??'';
    if($action==='club'){$db->prepare('UPDATE clubs SET name=?,address=?,phone=?,currency_symbol=? WHERE id=?')->execute([sanitize($_POST['name']),sanitize($_POST['address']),sanitize($_POST['phone']),sanitize($_POST['currency_symbol']?:'Rs.'),$club]);$_SESSION['club_name']=sanitize($_POST['name']);$flash='Club details updated.';}
    elseif($action==='table'){$db->prepare('INSERT INTO tables(club_id,table_number,table_name,table_type,rate_plan_id) VALUES(?,?,?,?,?)')->execute([$club,sanitize($_POST['table_number']),sanitize($_POST['table_name']),$_POST['table_type'],filter_var($_POST['rate_plan_id'],FILTER_VALIDATE_INT)?:null]);$flash='Table added.';}
    elseif($action==='rate'){$type=$_POST['billing_type'];$slab=$type==='slab'?json_encode([['up_to_minutes'=>(int)$_POST['slab_minutes'],'price'=>(float)$_POST['slab_price'],'per_extra_minutes'=>(int)$_POST['extra_minutes'],'extra_price'=>(float)$_POST['extra_price']]]):null;$db->prepare('INSERT INTO rate_plans(club_id,plan_name,billing_type,rate_per_minute,rate_per_frame,slab_config) VALUES(?,?,?,?,?,?)')->execute([$club,sanitize($_POST['plan_name']),$type,(float)$_POST['rate_per_minute'],(float)$_POST['rate_per_frame'],$slab]);$flash='Rate plan saved.';}
    elseif($action==='token'){$token=bin2hex(random_bytes(16));$db->prepare('UPDATE clubs SET tv_token=? WHERE id=?')->execute([$token,$club]);$flash='TV token regenerated.';}
}
$q=$db->prepare('SELECT * FROM clubs WHERE id=?');$q->execute([$club]);$c=$q->fetch();
$q=$db->prepare('SELECT * FROM rate_plans WHERE club_id=? ORDER BY plan_name');$q->execute([$club]);$plans=$q->fetchAll();
$q=$db->prepare('SELECT * FROM tables WHERE club_id=? ORDER BY table_number');$q->execute([$club]);$tables=$q->fetchAll();
$tabs=['club'=>['Club profile','fa-building'],'tables'=>['Tables','fa-table-cells-large'],'rates'=>['Rate plans','fa-calculator'],'tv'=>['TV display','fa-tv']];
?>
<div class="page-header"><div><p class="page-kicker">Club configuration</p><h1 class="page-title">Settings</h1><p class="page-description">Manage your club identity, table inventory, billing rules and in-club TV display.</p></div><span class="soft-pill"><i class="fa-solid fa-shield-halved text-green-300"></i> Owner & manager access</span></div>
<div class="tabs"><?php foreach($tabs as $key=>[$label,$icon]): ?><a class="tab-link <?=$tab===$key?'is-active':''?>" href="?tab=<?=$key?>"><i class="fa-solid <?=$icon?> mr-1"></i><?=$label?></a><?php endforeach; ?></div>
<?php if(isset($flash)): ?><div class="flash-success mt-5 max-w-3xl"><i class="fa-solid fa-circle-check mt-0.5"></i><?=sanitize($flash)?></div><?php endif; ?>
<?php if($tab==='club'): ?>
<div class="grid xl:grid-cols-[minmax(0,1fr)_300px] gap-5 mt-5 max-w-6xl"><form method="post" class="form-card"><div class="panel-head"><div><h2 class="form-card-title">Club profile</h2><p class="form-card-copy">These details appear across your private CuePOS workspace and receipts.</p></div></div><input type="hidden" name="csrf_token" value="<?=csrfToken()?>"><input type="hidden" name="action" value="club"><div class="grid sm:grid-cols-2 gap-4"><label class="sm:col-span-2"><span class="label">Club name</span><input class="input" name="name" value="<?=sanitize($c['name'])?>"></label><label class="sm:col-span-2"><span class="label">Address</span><input class="input" name="address" value="<?=sanitize($c['address'])?>" placeholder="Club address"></label><label><span class="label">Phone</span><input class="input" name="phone" value="<?=sanitize($c['phone'])?>" placeholder="0300 1234567"></label><label><span class="label">Currency symbol</span><input class="input" name="currency_symbol" value="<?=sanitize($c['currency_symbol'])?>" placeholder="Rs."></label></div><button class="btn-primary mt-6"><i class="fa-solid fa-floppy-disk"></i> Save club details</button></form><aside class="card"><h2 class="section-title">A consistent workspace</h2><p class="section-subtitle">Keep club identity details current so your team and players always see the right information.</p><div class="mt-5 space-y-3 text-xs text-slate-500"><p><i class="fa-solid fa-circle-check text-green-300 mr-2"></i>Name displayed in the workspace header.</p><p><i class="fa-solid fa-circle-check text-green-300 mr-2"></i>Currency used in reporting and billing.</p><p><i class="fa-solid fa-circle-check text-green-300 mr-2"></i>Address available for printed records.</p></div></aside></div>
<?php elseif($tab==='tables'): ?>
<div class="grid xl:grid-cols-[minmax(0,1fr)_320px] gap-5 mt-5"><section class="card"><div class="panel-head"><div><h2 class="section-title">Your table floor</h2><p class="section-subtitle">Add and review the tables your operators manage in the live floor view.</p></div><span class="soft-pill"><?=count($tables)?> active tables</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>#</th><th>Name</th><th>Type</th><th>Status</th></tr></thead><tbody><?php foreach($tables as $t):?><tr><td><span class="soft-pill"><?=sanitize($t['table_number'])?></span></td><td class="font-semibold text-slate-100"><?=sanitize($t['table_name'])?></td><td><?=sanitize(ucfirst($t['table_type']))?></td><td><span class="status-pill <?=in_array($t['status'],['available','running'])?'bg-green-400/10 text-green-300':'bg-slate-500/15 text-slate-400'?>"><?=sanitize($t['status'])?></span></td></tr><?php endforeach?></tbody></table></div></section><form method="post" class="form-card"><h2 class="form-card-title">Add a table</h2><p class="form-card-copy">Make it available to the floor in seconds.</p><input type="hidden" name="csrf_token" value="<?=csrfToken()?>"><input type="hidden" name="action" value="table"><div class="space-y-4 mt-5"><label><span class="label">Table number</span><input class="input" name="table_number" placeholder="For example, 9" required></label><label><span class="label">Display name</span><input class="input" name="table_name" placeholder="Table 9"></label><label><span class="label">Table type</span><select class="input" name="table_type"><option value="snooker">Snooker</option><option value="pool">Pool</option><option value="billiards">Billiards</option></select></label><label><span class="label">Rate plan</span><select class="input" name="rate_plan_id"><option value="">No rate plan yet</option><?php foreach($plans as $p):?><option value="<?=$p['id']?>"><?=sanitize($p['plan_name'])?></option><?php endforeach?></select></label></div><button class="btn-primary mt-5"><i class="fa-solid fa-plus"></i> Add table</button></form></div>
<?php elseif($tab==='rates'): ?>
<div class="grid xl:grid-cols-[minmax(0,1fr)_360px] gap-5 mt-5"><section class="card"><div class="panel-head"><div><h2 class="section-title">Billing rules</h2><p class="section-subtitle">Each plan can be attached to any table on your floor.</p></div><span class="soft-pill"><?=count($plans)?> plans</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Plan</th><th>Billing type</th><th>Per minute</th><th>Per frame</th></tr></thead><tbody><?php foreach($plans as $p):?><tr><td class="font-semibold text-slate-100"><?=sanitize($p['plan_name'])?></td><td><span class="soft-pill"><?=sanitize(str_replace('_',' ',$p['billing_type']))?></span></td><td><?=money($p['rate_per_minute'])?></td><td><?=money($p['rate_per_frame'])?></td></tr><?php endforeach?></tbody></table></div></section><form method="post" class="form-card"><h2 class="form-card-title">Create a rate plan</h2><p class="form-card-copy">Set clear pricing before your operators start sessions.</p><input type="hidden" name="csrf_token" value="<?=csrfToken()?>"><input type="hidden" name="action" value="rate"><div class="space-y-4 mt-5"><label><span class="label">Plan name</span><input class="input" name="plan_name" required placeholder="Evening premium"></label><label><span class="label">Billing type</span><select class="input" name="billing_type"><option value="per_minute">Per minute</option><option value="per_frame">Per frame</option><option value="slab">Slab</option><option value="challenge">Challenge only</option></select></label><div class="grid grid-cols-2 gap-3"><label><span class="label">Per minute</span><input class="input" type="number" name="rate_per_minute" step=".01" min="0" placeholder="10"></label><label><span class="label">Per frame</span><input class="input" type="number" name="rate_per_frame" step=".01" min="0" placeholder="180"></label><label><span class="label">Slab up to mins</span><input class="input" type="number" name="slab_minutes" min="1" value="60"></label><label><span class="label">Slab price</span><input class="input" type="number" name="slab_price" min="0" value="700"></label><label><span class="label">Extra minutes</span><input class="input" type="number" name="extra_minutes" min="1" value="15"></label><label><span class="label">Extra price</span><input class="input" type="number" name="extra_price" min="0" value="100"></label></div></div><button class="btn-primary mt-5"><i class="fa-solid fa-plus"></i> Save rate plan</button></form></div>
<?php else: ?>
<div class="grid xl:grid-cols-[minmax(0,1fr)_330px] gap-5 mt-5 max-w-6xl"><section class="form-card"><h2 class="form-card-title">TV display link</h2><p class="form-card-copy">Use this private, tokenised address on an in-club TV to share live table availability.</p><div class="mt-6"><span class="label">Display URL</span><div class="flex gap-2"><input class="input" readonly value="<?=url('tv.php?token='.$c['tv_token'])?>"><button type="button" class="btn-secondary" onclick="navigator.clipboard?.writeText(this.previousElementSibling.value);this.innerHTML='<i class=\'fa-solid fa-check\'></i>';" title="Copy link"><i class="fa-solid fa-copy"></i></button></div></div><form method="post" class="mt-6"><input type="hidden" name="csrf_token" value="<?=csrfToken()?>"><input type="hidden" name="action" value="token"><button class="btn-danger"><i class="fa-solid fa-rotate"></i> Regenerate display token</button></form></section><aside class="card"><h2 class="section-title">Keep this link private</h2><p class="section-subtitle">Anyone with the token can open the display. Regenerate it if it has been shared incorrectly.</p><div class="mt-5 rounded-xl border border-amber-400/20 bg-amber-400/5 p-4 text-xs text-amber-100 leading-5"><i class="fa-solid fa-triangle-exclamation text-amber-300 mr-1"></i> Regeneration disconnects old display links immediately.</div></aside></div>
<?php endif; ?>
<?php require __DIR__.'/../includes/footer.php'; ?>
