<?php
require_once __DIR__.'/includes/bootstrap.php';
$publicTitle='Contact CuePOS | Request a Snooker Club Software Demo';
$publicDescription='Contact CuePOS to request a demonstration or ask a question about snooker club management software.';
$publicCanonical=siteUrl('/contact.php');
$success='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    verifyCsrf();
    $name=sanitize($_POST['name']??'');$email=filter_var($_POST['email']??'',FILTER_VALIDATE_EMAIL);
    $club=sanitize($_POST['club_name']??'');$message=sanitize($_POST['message']??'');
    if(!$name||!$email||!$club){$error='Please complete your name, business email, and club name.';}
    else{try{$q=getDB()->prepare("INSERT INTO demo_requests(name,email,club_name,country_code,message,status) VALUES(?,?,?,?,?,'new')");$q->execute([$name,$email,$club,strtoupper(substr(sanitize($_POST['country_code']??''),0,2)),$message]);$success='Thanks — your request has been received. We will follow up through your business email.';}catch(Throwable $e){$error='Your request could not be saved yet. Please try again after the SaaS migration is installed.';}}
}
require __DIR__.'/includes/public-header.php';
?>
<main class="relative overflow-hidden">
    <div class="absolute inset-x-0 top-0 h-[25rem] bg-gradient-to-br from-emerald-50 via-white to-teal-50 -z-10"></div>
    <div class="max-w-6xl mx-auto px-5 py-16 lg:py-20 grid lg:grid-cols-[.88fr_1.12fr] gap-10 xl:gap-16 items-start">
        <section class="lg:pt-7"><span class="eyebrow"><span class="w-2 h-2 bg-cue rounded-full"></span>Talk to CuePOS</span><h1 class="font-display text-5xl lg:text-6xl font-extrabold tracking-tight leading-[.98] mt-6">See CuePOS in your <span class="text-cue">club context.</span></h1><p class="text-lg text-slate-600 mt-6 leading-8 max-w-xl">Tell us how your floor works today. We will show you the workflows that matter for your tables, staff, players, café and reporting.</p><div class="mt-10 space-y-4"><div class="public-card p-5"><i class="fa-solid fa-table-cells-large text-cue text-xl"></i><h2 class="font-display font-bold text-xl mt-3">A floor-first walkthrough</h2><p class="text-slate-500 text-sm mt-2 leading-6">See live table sessions, café charges and payment flow in a realistic club setup.</p></div><div class="public-card p-5"><i class="fa-solid fa-chart-line text-cue text-xl"></i><h2 class="font-display font-bold text-xl mt-3">A clear operating picture</h2><p class="text-slate-500 text-sm mt-2 leading-6">Explore the player, shift, expense and reporting views your owners will use every day.</p></div></div></section>
        <section class="form-shell"><div class="flex items-center gap-3"><span class="form-step"><i class="fa-solid fa-comment-dots"></i></span><div><p class="text-xs font-extrabold uppercase tracking-[.13em] text-cue-deep">Request a walkthrough</p><h2 class="font-display text-3xl font-bold tracking-tight mt-1">Tell us about your club</h2></div></div><?php if($success): ?><div class="form-message form-message-success mt-6 flex gap-3"><i class="fa-solid fa-circle-check mt-0.5"></i><span><?=sanitize($success)?></span></div><?php endif; ?><?php if($error): ?><div class="form-message form-message-error mt-6 flex gap-3"><i class="fa-solid fa-circle-exclamation mt-0.5"></i><span><?=sanitize($error)?></span></div><?php endif; ?><form method="post" class="mt-7"><input type="hidden" name="csrf_token" value="<?=csrfToken()?>"><div class="grid sm:grid-cols-2 gap-5"><label class="field"><span class="field-label">Your name <span class="field-hint">Required</span></span><input required class="field-control" autocomplete="name" name="name" placeholder="Hassan Ahmed" value="<?=sanitize($_POST['name']??'')?>"></label><label class="field"><span class="field-label">Business email <span class="field-hint">Required</span></span><input required class="field-control" autocomplete="email" type="email" name="email" placeholder="you@club.com" value="<?=sanitize($_POST['email']??'')?>"></label><label class="field sm:col-span-2"><span class="field-label">Club name <span class="field-hint">Required</span></span><input required class="field-control" autocomplete="organization" name="club_name" placeholder="Your snooker club" value="<?=sanitize($_POST['club_name']??'')?>"></label><label class="field"><span class="field-label">Country code <span class="field-hint">2 letters</span></span><input class="field-control uppercase" maxlength="2" name="country_code" placeholder="PK" value="<?=sanitize($_POST['country_code']??'')?>"></label><div class="hidden sm:block"></div><label class="field sm:col-span-2"><span class="field-label">What would you like to improve? <span class="field-hint">Optional</span></span><textarea class="field-control field-textarea" name="message" placeholder="For example: 12 tables, a café, two shifts and loyalty members."><?=sanitize($_POST['message']??'')?></textarea></label></div><button class="btn-public btn-public-primary w-full mt-7">Request a focused demo <i class="fa-solid fa-arrow-right"></i></button><div class="form-trust"><i class="fa-solid fa-lock"></i><span>We use your details only to respond to your CuePOS enquiry. Review our <a class="marketing-link" href="<?=url('privacy.php')?>">Privacy Policy</a>.</span></div></form></section>
    </div>
</main>
<?php require __DIR__.'/includes/public-footer.php'; ?>
