<?php
$pageTitle='Dashboard';
require_once __DIR__.'/includes/header.php';
require_once __DIR__.'/includes/sidebar.php';
$db=getDB();$club=$_SESSION['club_id'];
$today=$db->prepare("SELECT COALESCE(SUM(total_amount),0) FROM sessions WHERE club_id=? AND status='completed' AND DATE(end_time)=CURDATE()");$today->execute([$club]);$revenue=(float)$today->fetchColumn();
$active=$db->prepare("SELECT COUNT(*) FROM sessions WHERE club_id=? AND status IN ('running','paused')");$active->execute([$club]);$activeSessions=(int)$active->fetchColumn();
$expensesQ=$db->prepare('SELECT COALESCE(SUM(amount),0) FROM expenses WHERE club_id=? AND expense_date=CURDATE()');$expensesQ->execute([$club]);$expenses=(float)$expensesQ->fetchColumn();
$playersQ=$db->prepare('SELECT COUNT(*) FROM players WHERE club_id=? AND is_active=1');$playersQ->execute([$club]);$players=(int)$playersQ->fetchColumn();
$month=$db->prepare("SELECT COALESCE(SUM(total_amount),0) FROM sessions WHERE club_id=? AND status='completed' AND DATE_FORMAT(end_time,'%Y-%m')=DATE_FORMAT(CURDATE(),'%Y-%m')");$month->execute([$club]);$monthly=(float)$month->fetchColumn();
$cafeQ=$db->prepare("SELECT COALESCE(SUM(total_amount),0) FROM cafe_orders WHERE club_id=? AND status='completed' AND DATE(created_at)=CURDATE()");$cafeQ->execute([$club]);$cafe=(float)$cafeQ->fetchColumn();
$daily=$db->prepare("SELECT DATE(end_time) d,SUM(total_amount) total FROM sessions WHERE club_id=? AND status='completed' AND end_time >= DATE_SUB(CURDATE(), INTERVAL 30 DAY) GROUP BY DATE(end_time) ORDER BY d");$daily->execute([$club]);$chart=$daily->fetchAll();
?>
<div class="page-header"><div><p class="page-kicker">Owner overview</p><h1 class="page-title">Good day, <?=sanitize(explode(' ',$_SESSION['user_name'])[0])?>.</h1><p class="page-description">Your live snapshot of tables, revenue and club activity for <?=date('l, j F')?>.</p></div><a href="<?=url('operator.php')?>" class="btn-primary"><i class="fa-solid fa-table-cells-large"></i> Open live floor</a></div>
<div class="grid grid-cols-2 xl:grid-cols-4 gap-4"><article class="card metric-card"><p class="metric-label">Today’s revenue</p><p class="metric-value text-green-300"><?=money($revenue)?></p><p class="metric-note"><i class="fa-solid fa-arrow-trend-up text-green-400"></i> Completed table sessions</p></article><article class="card metric-card"><p class="metric-label">Active tables</p><p class="metric-value text-red-300"><?=$activeSessions?></p><p class="metric-note"><i class="fa-solid fa-circle text-[.42rem] text-red-400"></i> Running or paused right now</p></article><article class="card metric-card"><p class="metric-label">Today’s expenses</p><p class="metric-value text-orange-300"><?=money($expenses)?></p><p class="metric-note"><i class="fa-solid fa-receipt text-orange-300"></i> Recorded operating costs</p></article><article class="card metric-card"><p class="metric-label">Net position</p><p class="metric-value text-emerald-300"><?=money($revenue-$expenses)?></p><p class="metric-note"><i class="fa-solid fa-wallet text-emerald-300"></i> Revenue less today’s expenses</p></article></div>
<div class="grid md:grid-cols-3 gap-4 mt-4"><article class="card"><p class="metric-label">This month</p><p class="text-xl font-extrabold mt-2"><?=money($monthly)?></p><p class="metric-note">Completed session revenue</p></article><article class="card"><p class="metric-label">Active players</p><p class="text-xl font-extrabold mt-2"><?=$players?></p><p class="metric-note">Members and regular guests</p></article><article class="card"><p class="metric-label">Café sales today</p><p class="text-xl font-extrabold mt-2"><?=money($cafe)?></p><p class="metric-note">Completed café orders</p></article></div>
<div class="grid xl:grid-cols-5 gap-4 mt-5"><section class="card xl:col-span-3"><div class="panel-head"><div><h2 class="section-title">Revenue trend</h2><p class="section-subtitle">Completed session revenue across the last 30 days.</p></div><span class="soft-pill"><i class="fa-solid fa-chart-line text-green-300"></i> 30 days</span></div><div class="h-64"><canvas id="revenueChart"></canvas></div></section><section class="card xl:col-span-2"><div class="panel-head"><div><h2 class="section-title">Today’s mix</h2><p class="section-subtitle">Where today’s sales are coming from.</p></div></div><div class="h-64"><canvas id="sourceChart"></canvas></div></section></div>
<section class="card mt-5"><div class="panel-head"><div><h2 class="section-title">Quick actions</h2><p class="section-subtitle">Common owner and manager tasks, one click away.</p></div><span class="soft-pill"><i class="fa-solid fa-bolt text-amber-300"></i> Live workspace</span></div><div class="flex flex-wrap gap-2"><a class="btn-secondary" href="<?=url('modules/expenses.php')?>"><i class="fa-solid fa-plus text-orange-300"></i> Add expense</a><a class="btn-secondary" href="<?=url('modules/players.php')?>"><i class="fa-solid fa-user-plus text-green-300"></i> Add player</a><a class="btn-secondary" href="<?=url('modules/reports.php')?>"><i class="fa-solid fa-chart-line text-blue-300"></i> View reports</a><a class="btn-secondary" href="<?=url('modules/shifts.php')?>"><i class="fa-solid fa-cash-register text-purple-300"></i> Manage shifts</a></div></section>
<script>
const chartText='#91a5b7',chartGrid='#263a51';
new Chart(document.getElementById('revenueChart'),{type:'line',data:{labels:<?=json_encode(array_column($chart,'d'))?>,datasets:[{label:'Revenue',data:<?=json_encode(array_map('floatval',array_column($chart,'total')))?>,borderColor:'#2ed68e',backgroundColor:'rgba(46,214,142,.12)',borderWidth:2,fill:true,tension:.38,pointRadius:0,pointHoverRadius:4}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{backgroundColor:'#101d2d',borderColor:'#263a51',borderWidth:1,titleColor:'#eff7f5',bodyColor:'#b9c9d1'}},scales:{x:{ticks:{color:chartText,maxTicksLimit:6},grid:{display:false},border:{display:false}},y:{ticks:{color:chartText},grid:{color:chartGrid},border:{display:false}}}}});
new Chart(document.getElementById('sourceChart'),{type:'doughnut',data:{labels:['Tables','Café'],datasets:[{data:[<?=$revenue?>,<?=$cafe?>],backgroundColor:['#2ed68e','#61a6ff'],borderColor:'#111d2c',borderWidth:6,hoverOffset:5}]},options:{responsive:true,maintainAspectRatio:false,cutout:'70%',plugins:{legend:{position:'bottom',labels:{color:chartText,usePointStyle:true,padding:18}},tooltip:{backgroundColor:'#101d2d',borderColor:'#263a51',borderWidth:1,titleColor:'#eff7f5',bodyColor:'#b9c9d1'}}}});
</script>
<?php require __DIR__.'/includes/footer.php'; ?>
