<?php
$pageTitle='Dashboard';
require_once __DIR__.'/includes/header.php';
require_once __DIR__.'/includes/sidebar.php';
$db=getDB();$club=$_SESSION['club_id'];
$today=$db->prepare("SELECT COALESCE(SUM(total_amount),0) FROM sessions WHERE club_id=? AND status='completed' AND DATE(end_time)=CURDATE()");$today->execute([$club]);$revenue=(float)$today->fetchColumn();
$active=$db->prepare("SELECT COUNT(*) FROM sessions WHERE club_id=? AND status IN ('running','paused')");$active->execute([$club]);$activeSessions=(int)$active->fetchColumn();
$expensesQ=$db->prepare('SELECT COALESCE(SUM(amount),0) FROM expenses WHERE club_id=? AND expense_date=CURDATE()');$expensesQ->execute([$club]);$expenses=(float)$expensesQ->fetchColumn();
$playersQ=$db->prepare('SELECT COUNT(*) FROM players WHERE club_id=? AND is_active=1');$playersQ->execute([$club]);$players=(int)$playersQ->fetchColumn();
$month=$db->prepare("SELECT COALESCE(SUM(total_amount),0) FROM sessions WHERE club_id=? AND status='completed' AND DATE_FORMAT(end_time,'%Y-%m')=DATE_FORMAT(CURDATE(),'%Y-%m')");$month->execute([$club]);$monthly=(float)$month->fetchColumn();
$cafeQ=$db->prepare("SELECT COALESCE(SUM(total_amount),0) FROM cafe_orders WHERE club_id=? AND status='completed' AND DATE(created_at)=CURDATE()");$cafeQ->execute([$club]);$cafe=(float)$cafeQ->fetchColumn();
$tableQ=$db->prepare("SELECT status,COUNT(*) count FROM tables WHERE club_id=? AND is_active=1 GROUP BY status");$tableQ->execute([$club]);$floor=[];foreach($tableQ as $row)$floor[$row['status']]=(int)$row['count'];$available=$floor['available']??0;$paused=$floor['paused']??0;$held=$floor['held']??0;
$daily=$db->prepare("SELECT DATE(end_time) d,SUM(total_amount) total FROM sessions WHERE club_id=? AND status='completed' AND end_time >= DATE_SUB(CURDATE(), INTERVAL 30 DAY) GROUP BY DATE(end_time) ORDER BY d");$daily->execute([$club]);$chart=$daily->fetchAll();
?>
<div class="page-header dashboard-heading"><div><p class="page-kicker">Daily operations</p><h1 class="page-title">Club performance</h1><p class="page-description"><?=date('l, j F Y')?> · Review the floor, sales and costs before the next shift.</p></div><div class="flex items-center gap-2"><span class="soft-pill hidden sm:inline-flex"><i class="fa-solid fa-clock text-slate-300"></i> Live updates</span><a href="<?=url('operator.php')?>" class="btn-primary"><i class="fa-solid fa-table-cells-large"></i> Manage tables</a></div></div>
<div class="grid grid-cols-2 xl:grid-cols-4 gap-4"><article class="dashboard-metric"><div class="dashboard-metric-top"><span class="dashboard-metric-icon is-green"><i class="fa-solid fa-arrow-trend-up"></i></span><span class="metric-label">Table revenue</span></div><p class="dashboard-metric-value"><?=money($revenue)?></p><p class="dashboard-metric-note">Completed sessions today</p></article><article class="dashboard-metric"><div class="dashboard-metric-top"><span class="dashboard-metric-icon is-blue"><i class="fa-solid fa-table-cells-large"></i></span><span class="metric-label">Tables in play</span></div><p class="dashboard-metric-value"><?=$activeSessions?></p><p class="dashboard-metric-note"><?=$available?> available · <?=$paused?> paused</p></article><article class="dashboard-metric"><div class="dashboard-metric-top"><span class="dashboard-metric-icon is-amber"><i class="fa-solid fa-receipt"></i></span><span class="metric-label">Operating costs</span></div><p class="dashboard-metric-value"><?=money($expenses)?></p><p class="dashboard-metric-note">Expenses recorded today</p></article><article class="dashboard-metric"><div class="dashboard-metric-top"><span class="dashboard-metric-icon is-teal"><i class="fa-solid fa-wallet"></i></span><span class="metric-label">Net cash position</span></div><p class="dashboard-metric-value"><?=money($revenue-$expenses)?></p><p class="dashboard-metric-note">Sales less recorded expenses</p></article></div>
<section class="dashboard-operations mt-4"><div class="dashboard-operations-copy"><span class="dashboard-metric-icon is-slate"><i class="fa-solid fa-clipboard-check"></i></span><div><h2>Floor status</h2><p>Use the live floor to start sessions, hold bills and settle payments without leaving the shift workflow.</p></div></div><div class="dashboard-statuses"><span><b><?=$available?></b> available</span><span><b><?=$activeSessions?></b> in play</span><span><b><?=$held?></b> held bills</span></div><a href="<?=url('operator.php')?>" class="btn-secondary">Open floor <i class="fa-solid fa-arrow-right"></i></a></section>
<div class="grid md:grid-cols-3 gap-4 mt-4"><article class="dashboard-secondary"><span class="metric-label">Month-to-date revenue</span><p><?=money($monthly)?></p><small>Completed session revenue</small></article><article class="dashboard-secondary"><span class="metric-label">Active players</span><p><?=$players?></p><small>Members and regular guests</small></article><article class="dashboard-secondary"><span class="metric-label">Café sales today</span><p><?=money($cafe)?></p><small>Completed café orders</small></article></div>
<div class="grid xl:grid-cols-5 gap-4 mt-5"><section class="dashboard-panel xl:col-span-3"><div class="panel-head"><div><h2 class="section-title">Revenue performance</h2><p class="section-subtitle">Daily completed session revenue for the last 30 days.</p></div><span class="soft-pill">30 days</span></div><div class="h-64"><canvas id="revenueChart"></canvas></div></section><section class="dashboard-panel xl:col-span-2"><div class="panel-head"><div><h2 class="section-title">Sales breakdown</h2><p class="section-subtitle">Table sessions and café orders recorded today.</p></div></div><div class="h-64"><canvas id="sourceChart"></canvas></div></section></div>
<section class="dashboard-panel mt-5"><div class="panel-head"><div><h2 class="section-title">Operations shortcuts</h2><p class="section-subtitle">Common tasks for owners and managers.</p></div></div><div class="flex flex-wrap gap-2"><a class="btn-secondary" href="<?=url('modules/expenses.php')?>"><i class="fa-solid fa-plus text-amber-300"></i> Record expense</a><a class="btn-secondary" href="<?=url('modules/players.php')?>"><i class="fa-solid fa-user-plus text-teal-300"></i> Add player</a><a class="btn-secondary" href="<?=url('modules/reports.php')?>"><i class="fa-solid fa-chart-line text-blue-300"></i> Financial reports</a><a class="btn-secondary" href="<?=url('modules/shifts.php')?>"><i class="fa-solid fa-cash-register text-purple-300"></i> Shift management</a></div></section>
<script>
const chartText='#91a5b7',chartGrid='#263a51';
new Chart(document.getElementById('revenueChart'),{type:'line',data:{labels:<?=json_encode(array_column($chart,'d'))?>,datasets:[{label:'Revenue',data:<?=json_encode(array_map('floatval',array_column($chart,'total')))?>,borderColor:'#29b987',backgroundColor:'rgba(41,185,135,.09)',borderWidth:2.25,fill:true,tension:.35,pointRadius:0,pointHoverRadius:4,pointHoverBackgroundColor:'#f7fffb'}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{backgroundColor:'#101d2d',borderColor:'#2b425a',borderWidth:1,titleColor:'#eff7f5',bodyColor:'#b9c9d1'}},scales:{x:{ticks:{color:chartText,maxTicksLimit:6},grid:{display:false},border:{display:false}},y:{ticks:{color:chartText},grid:{color:chartGrid},border:{display:false}}}}});
new Chart(document.getElementById('sourceChart'),{type:'doughnut',data:{labels:['Table sessions','Café sales'],datasets:[{data:[<?=$revenue?>,<?=$cafe?>],backgroundColor:['#29b987','#4f91dc'],borderColor:'#101d2d',borderWidth:6,hoverOffset:4}]},options:{responsive:true,maintainAspectRatio:false,cutout:'72%',plugins:{legend:{position:'bottom',labels:{color:chartText,usePointStyle:true,padding:18}},tooltip:{backgroundColor:'#101d2d',borderColor:'#2b425a',borderWidth:1,titleColor:'#eff7f5',bodyColor:'#b9c9d1'}}}});
</script>
<?php require __DIR__.'/includes/footer.php'; ?>
