<?php
require_once __DIR__.'/config/db.php';startAppSession();
$publicTitle='CuePOS Pakistan Pricing | Snooker Club Software';
$publicDescription='Simple, affordable CuePOS plans for Pakistani snooker clubs: start free, grow with Basic, or run the complete club with Pro.';
$publicCanonical=siteUrl('/pricing.php');
require __DIR__.'/includes/public-header.php';
$plans=publicPlans();
$benefits=[
    'free'=>['1 table','Basic session billing','A simple way to get started'],
    'basic'=>['Up to 5 tables','Reliable daily billing','Player records and core operations'],
    'pro'=>['Unlimited tables','Café & menu operations','Reports and full club management']
];
?>
<main class="relative overflow-hidden"><div class="absolute inset-x-0 top-0 h-[29rem] bg-gradient-to-br from-emerald-50 via-white to-teal-50 -z-10"></div><section class="public-section text-center pt-16 lg:pt-20"><div class="public-page-head"><span class="eyebrow"><span class="w-2 h-2 bg-cue rounded-full"></span>Pakistan pricing</span><h1 class="font-display text-5xl md:text-6xl font-extrabold mt-6">Simple plans for <span class="text-cue">serious club operations.</span></h1><p class="text-lg text-slate-600 max-w-2xl mx-auto mt-6 leading-8">Start with one table at no cost. Upgrade only when your snooker club needs more tables, café operations and reporting.</p></div><div class="grid lg:grid-cols-3 gap-5 mt-14 text-left max-w-6xl mx-auto"><?php foreach($plans as $plan): $slug=$plan['slug'];$isPro=$slug==='pro';$planBenefits=$benefits[$slug]??['Club management tools','Secure workspace','Professional support']; ?><article class="relative rounded-[1.5rem] p-7 <?=$isPro?'pricing-pro text-white shadow-2xl shadow-slate-900/20':'public-card'?>"><?php if($isPro): ?><span class="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-cue px-3 py-1 text-[.68rem] font-extrabold uppercase tracking-[.1em] text-ink">Most popular</span><?php endif; ?><p class="text-sm font-extrabold <?=$isPro?'text-cue':'text-emerald-700'?>"><?=sanitize($plan['name'])?></p><h2 class="font-display text-3xl font-bold mt-3"><?=sanitize($plan['tagline'] ?: 'For your club')?></h2><p class="mt-4 <?=$isPro?'text-slate-300':'text-slate-600'?> min-h-[3.5rem] leading-6"><?=sanitize($plan['description'])?></p><div class="mt-7 flex items-end gap-2"><?php if((float)$plan['price_monthly']>0): ?><b class="font-display text-4xl">Rs. <?=number_format($plan['price_monthly'],0)?></b><span class="mb-1 <?=$isPro?'text-slate-300':'text-slate-500'?>">/ month</span><?php else: ?><b class="font-display text-4xl">Free</b><span class="mb-1 <?=$isPro?'text-slate-300':'text-slate-500'?>">forever</span><?php endif; ?></div><div class="my-7 border-t <?=$isPro?'border-white/15':'border-slate-200'?>"></div><ul class="space-y-4 text-sm"><?php foreach($planBenefits as $benefit): ?><li class="flex gap-3 <?=$isPro?'text-slate-100':'text-slate-700'?>"><i class="fa-solid fa-circle-check <?=$isPro?'text-cue':'text-emerald-600'?> mt-0.5"></i><span><?=$benefit?></span></li><?php endforeach; ?></ul><a href="<?=url('trial.php?plan='.urlencode($slug))?>" class="btn-public w-full mt-8 <?=$isPro?'btn-public-accent':'btn-public-primary'?>"><?=$slug==='free'?'Start free':'Choose '.sanitize($plan['name'])?><i class="fa-solid fa-arrow-right"></i></a></article><?php endforeach; ?></div><div class="mt-10 max-w-3xl mx-auto rounded-2xl border border-emerald-100 bg-emerald-50/70 px-5 py-4 text-sm text-emerald-900"><i class="fa-solid fa-circle-info text-emerald-700 mr-2"></i>All plans are priced in Pakistani Rupees. You can begin with the Free Plan and upgrade your club workspace when you are ready.</div></section></main>
<?php require __DIR__.'/includes/public-footer.php'; ?>
