<?php
$pageTitle='CuePOS Platform';
require_once __DIR__.'/../includes/header.php';
require_once __DIR__.'/../includes/sidebar.php';
requirePlatformAdmin();
$db=getDB();$stats=[];
foreach(['clubs'=>'SELECT COUNT(*) FROM clubs','trials'=>"SELECT COUNT(*) FROM subscriptions WHERE status='trial' AND trial_ends_at>=NOW()",'paid'=>"SELECT COUNT(*) FROM subscriptions WHERE status='active'",'leads'=>"SELECT COUNT(*) FROM demo_requests WHERE status='new'"] as $k=>$sql){try{$stats[$k]=(int)$db->query($sql)->fetchColumn();}catch(Throwable $e){$stats[$k]=0;}}
$clubs=$db->query("SELECT c.*,p.name plan_name,s.status subscription_status,s.trial_ends_at FROM clubs c LEFT JOIN subscriptions s ON s.id=(SELECT ss.id FROM subscriptions ss WHERE ss.club_id=c.id ORDER BY ss.id DESC LIMIT 1) LEFT JOIN plans p ON p.id=s.plan_id ORDER BY c.created_at DESC LIMIT 100")->fetchAll();
?>
<div class="page-header"><div><p class="page-kicker">Platform owner</p><h1 class="page-title">CuePOS SaaS console</h1><p class="page-description">Monitor global club workspaces, trials, subscriptions and inbound demand.</p></div><a href="<?=url('platform/settings.php')?>" class="btn-primary"><i class="fa-solid fa-gear"></i> Platform settings</a></div>
<div class="grid grid-cols-2 xl:grid-cols-4 gap-4"><?php foreach([['Club workspaces',$stats['clubs'],'fa-building','text-green-300'],['Active trials',$stats['trials'],'fa-hourglass-half','text-amber-200'],['Paid subscriptions',$stats['paid'],'fa-credit-card','text-blue-300'],['New demo leads',$stats['leads'],'fa-comment-dots','text-purple-300']] as [$label,$value,$icon,$color]): ?><article class="card metric-card"><p class="metric-label"><?=$label?></p><div class="flex items-end justify-between mt-2"><p class="metric-value <?=$color?>"><?=$value?></p><span class="w-9 h-9 grid place-items-center rounded-xl bg-white/5 text-slate-400"><i class="fa-solid <?=$icon?>"></i></span></div></article><?php endforeach; ?></div>
<section class="card mt-5"><div class="panel-head"><div><h2 class="section-title">Club tenants</h2><p class="section-subtitle">The latest 100 workspaces created on your CuePOS platform.</p></div><span class="soft-pill"><i class="fa-solid fa-globe text-green-300"></i> Global workspace view</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Club</th><th>Tenant slug</th><th>Country</th><th>Status</th><th>Plan</th><th>Trial ends</th><th>Created</th></tr></thead><tbody><?php foreach($clubs as $c): ?><tr><td class="font-semibold text-slate-100"><?=sanitize($c['name'])?></td><td><span class="soft-pill lowercase"><?=sanitize($c['slug']?:'—')?></span></td><td><?=sanitize($c['country_code']?:'—')?></td><td><span class="status-pill <?=($c['tenant_status']??'active')==='trial'?'bg-amber-400/10 text-amber-200':'bg-green-400/10 text-green-300'?>"><?=sanitize($c['tenant_status']??'active')?></span></td><td><?=sanitize($c['plan_name']?:'—')?></td><td><?=$c['trial_ends_at']?date('d M Y',strtotime($c['trial_ends_at'])):'—'?></td><td><?=date('d M Y',strtotime($c['created_at']))?></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php require __DIR__.'/../includes/footer.php'; ?>
