<?php
$pageTitle='Platform Settings';
require_once __DIR__.'/../includes/header.php';
require_once __DIR__.'/../includes/sidebar.php';
requirePlatformAdmin();
$db=getDB();$message='';
if($_SERVER['REQUEST_METHOD']==='POST'){verifyCsrf();foreach(['google_site_verification','support_email','public_site_url'] as $key){$value=trim($_POST[$key]??'');$q=$db->prepare("INSERT INTO platform_settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value),updated_at=NOW()");$q->execute([$key,$value]);}$message='Platform settings saved.';}
$settings=[];try{foreach($db->query('SELECT setting_key,setting_value FROM platform_settings') as $row)$settings[$row['setting_key']]=$row['setting_value'];}catch(Throwable $e){}
?>
<div class="page-header"><div><p class="page-kicker">Platform owner</p><h1 class="page-title">Platform settings</h1><p class="page-description">Manage the public CuePOS presence, support contact and search-verification values.</p></div><a href="<?=url('platform/index.php')?>" class="btn-secondary"><i class="fa-solid fa-arrow-left"></i> SaaS console</a></div>
<div class="grid xl:grid-cols-[1.1fr_.9fr] gap-5 max-w-6xl"><?php if($message): ?><div class="flash-success xl:col-span-2"><i class="fa-solid fa-circle-check mt-0.5"></i><?=$message?></div><?php endif; ?><form method="post" class="form-card"><div class="panel-head"><div><h2 class="form-card-title">Public publishing settings</h2><p class="form-card-copy">Use final production values only after the CuePOS domain is deployed over HTTPS.</p></div><span class="soft-pill"><i class="fa-solid fa-shield-halved text-green-300"></i> Owner only</span></div><input type="hidden" name="csrf_token" value="<?=csrfToken()?>"><div class="space-y-5"><label><span class="label">Public site URL</span><input class="input" name="public_site_url" value="<?=sanitize($settings['public_site_url']??siteUrl('/'))?>" placeholder="https://cuepos.com"><p class="text-xs text-slate-500 mt-2">Used for canonical links, sitemap URLs and public search metadata.</p></label><label><span class="label">Google site verification token</span><input class="input" name="google_site_verification" value="<?=sanitize($settings['google_site_verification']??'')?>" placeholder="Paste only the token from Search Console"><p class="text-xs text-slate-500 mt-2">CuePOS adds this token to the public site’s verification meta tag.</p></label><label><span class="label">Support email</span><input class="input" type="email" name="support_email" value="<?=sanitize($settings['support_email']??'')?>" placeholder="support@cuepos.com"></label></div><button class="btn-primary mt-6"><i class="fa-solid fa-floppy-disk"></i> Save platform settings</button></form><aside class="card"><h2 class="section-title">Before launch</h2><p class="section-subtitle">Complete these essentials before advertising CuePOS publicly.</p><div class="mt-5 space-y-4 text-sm"><div class="flex gap-3"><span class="w-7 h-7 grid place-items-center rounded-lg bg-green-400/10 text-green-300 shrink-0"><i class="fa-solid fa-globe"></i></span><div><b class="text-slate-200">Final domain and HTTPS</b><p class="text-slate-500 text-xs mt-1 leading-5">Confirm the canonical public address is live before adding it to Search Console.</p></div></div><div class="flex gap-3"><span class="w-7 h-7 grid place-items-center rounded-lg bg-blue-400/10 text-blue-300 shrink-0"><i class="fa-solid fa-sitemap"></i></span><div><b class="text-slate-200">Sitemap submission</b><p class="text-slate-500 text-xs mt-1 leading-5">Submit the published `/sitemap.xml` after ownership verification succeeds.</p></div></div><div class="flex gap-3"><span class="w-7 h-7 grid place-items-center rounded-lg bg-amber-400/10 text-amber-200 shrink-0"><i class="fa-solid fa-file-signature"></i></span><div><b class="text-slate-200">Legal and support details</b><p class="text-slate-500 text-xs mt-1 leading-5">Review the legal templates and give customers a monitored support address.</p></div></div></div></aside></div>
<?php require __DIR__.'/../includes/footer.php'; ?>
