-- CuePOS clean installer
-- WARNING: Use only for a new or failed installation with NO real club data.
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `platform_settings`;
DROP TABLE IF EXISTS `demo_requests`;
DROP TABLE IF EXISTS `trial_signups`;
DROP TABLE IF EXISTS `club_memberships`;
DROP TABLE IF EXISTS `subscriptions`;
DROP TABLE IF EXISTS `plans`;
DROP TABLE IF EXISTS `notifications`;
DROP TABLE IF EXISTS `audit_log`;
DROP TABLE IF EXISTS `settings`;
DROP TABLE IF EXISTS `leaderboard_entries`;
DROP TABLE IF EXISTS `tournament_matches`;
DROP TABLE IF EXISTS `tournament_players`;
DROP TABLE IF EXISTS `tournaments`;
DROP TABLE IF EXISTS `inventory_log`;
DROP TABLE IF EXISTS `inventory_items`;
DROP TABLE IF EXISTS `expenses`;
DROP TABLE IF EXISTS `cafe_order_items`;
DROP TABLE IF EXISTS `cafe_orders`;
DROP TABLE IF EXISTS `cafe_items`;
DROP TABLE IF EXISTS `held_bills`;
DROP TABLE IF EXISTS `session_frames`;
DROP TABLE IF EXISTS `player_loyalty_log`;
DROP TABLE IF EXISTS `sessions`;
DROP TABLE IF EXISTS `shifts`;
DROP TABLE IF EXISTS `players`;
DROP TABLE IF EXISTS `tables`;
DROP TABLE IF EXISTS `rate_plans`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `clubs`;
SET FOREIGN_KEY_CHECKS=1;

-- Core CuePOS schema
SET NAMES utf8mb4; SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE clubs (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(150) NOT NULL,address VARCHAR(255),phone VARCHAR(40),logo_path VARCHAR(255),tv_token CHAR(32) NOT NULL UNIQUE,loyalty_points_rate DECIMAL(10,2) NOT NULL DEFAULT 10,loyalty_redemption_rate DECIMAL(10,2) NOT NULL DEFAULT 1,currency_symbol VARCHAR(10) NOT NULL DEFAULT 'Rs.',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE users (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,club_id INT UNSIGNED NOT NULL,name VARCHAR(120) NOT NULL,email VARCHAR(190) NOT NULL,password VARCHAR(255) NOT NULL,role ENUM('owner','manager','cashier','operator') NOT NULL DEFAULT 'operator',is_active TINYINT(1) NOT NULL DEFAULT 1,last_login DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_user_email (email),KEY idx_users_club (club_id),CONSTRAINT fk_users_club FOREIGN KEY(club_id) REFERENCES clubs(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE rate_plans (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,club_id INT UNSIGNED NOT NULL,plan_name VARCHAR(100) NOT NULL,billing_type ENUM('per_minute','slab','per_frame','challenge') NOT NULL,rate_per_minute DECIMAL(10,2) NOT NULL DEFAULT 0,rate_per_frame DECIMAL(10,2) NOT NULL DEFAULT 0,slab_config JSON NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_rate_club (club_id),CONSTRAINT fk_rate_club FOREIGN KEY(club_id) REFERENCES clubs(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE tables (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,club_id INT UNSIGNED NOT NULL,table_number VARCHAR(20) NOT NULL,table_name VARCHAR(100),table_type ENUM('snooker','pool','billiards') NOT NULL DEFAULT 'snooker',status ENUM('available','running','paused','held','closed') NOT NULL DEFAULT 'available',rate_plan_id INT UNSIGNED NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_table_number (club_id,table_number),KEY idx_table_club_status(club_id,status),CONSTRAINT fk_table_club FOREIGN KEY(club_id) REFERENCES clubs(id) ON DELETE CASCADE,CONSTRAINT fk_table_rate FOREIGN KEY(rate_plan_id) REFERENCES rate_plans(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE players (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,club_id INT UNSIGNED NOT NULL,name VARCHAR(120) NOT NULL,phone VARCHAR(40),email VARCHAR(190),photo_path VARCHAR(255),date_of_birth DATE NULL,tier ENUM('regular','silver','gold','platinum') NOT NULL DEFAULT 'regular',loyalty_points INT NOT NULL DEFAULT 0,total_spent DECIMAL(12,2) NOT NULL DEFAULT 0,total_visits INT NOT NULL DEFAULT 0,ledger_balance DECIMAL(12,2) NOT NULL DEFAULT 0,member_rate_override DECIMAL(5,2) NOT NULL DEFAULT 0,joined_date DATE NULL,last_visit DATETIME NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,notes TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_player_club_name(club_id,name),KEY idx_player_phone(club_id,phone),CONSTRAINT fk_player_club FOREIGN KEY(club_id) REFERENCES clubs(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE shifts (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,club_id INT UNSIGNED NOT NULL,operator_id INT UNSIGNED NOT NULL,start_time DATETIME NOT NULL,end_time DATETIME NULL,opening_cash DECIMAL(12,2) NOT NULL DEFAULT 0,closing_cash DECIMAL(12,2) NULL,expected_cash DECIMAL(12,2) NULL,cash_discrepancy DECIMAL(12,2) NULL,total_revenue DECIMAL(12,2) NOT NULL DEFAULT 0,total_transactions INT NOT NULL DEFAULT 0,status ENUM('open','closed') NOT NULL DEFAULT 'open',notes TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY idx_shift_club_status(club_id,status),CONSTRAINT fk_shift_club FOREIGN KEY(club_id) REFERENCES clubs(id) ON DELETE CASCADE,CONSTRAINT fk_shift_user FOREIGN KEY(operator_id) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE sessions (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,club_id INT UNSIGNED NOT NULL,table_id INT UNSIGNED NOT NULL,player_id INT UNSIGNED NULL,player_name_walkin VARCHAR(120),operator_id INT UNSIGNED NOT NULL,shift_id INT UNSIGNED NULL,start_time DATETIME NOT NULL,end_time DATETIME NULL,pause_start DATETIME NULL,total_pause_seconds INT NOT NULL DEFAULT 0,billing_type ENUM('per_minute','slab','per_frame','challenge') NOT NULL,rate_plan_id INT UNSIGNED NULL,frames_played INT NOT NULL DEFAULT 0,challenge_amount DECIMAL(12,2) NOT NULL DEFAULT 0,table_amount DECIMAL(12,2) NOT NULL DEFAULT 0,cafe_amount DECIMAL(12,2) NOT NULL DEFAULT 0,total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0,points_used INT NOT NULL DEFAULT 0,points_earned INT NOT NULL DEFAULT 0,payment_method ENUM('cash','jazzcash','easypaisa','ledger','mixed') NULL,status ENUM('running','paused','held','completed','cancelled') NOT NULL DEFAULT 'running',notes TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_session_club_status(club_id,status),KEY idx_session_table_status(table_id,status),KEY idx_session_dates(club_id,end_time),CONSTRAINT fk_session_club FOREIGN KEY(club_id) REFERENCES clubs(id) ON DELETE CASCADE,CONSTRAINT fk_session_table FOREIGN KEY(table_id) REFERENCES tables(id),CONSTRAINT fk_session_player FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE SET NULL,CONSTRAINT fk_session_operator FOREIGN KEY(operator_id) REFERENCES users(id),CONSTRAINT fk_session_shift FOREIGN KEY(shift_id) REFERENCES shifts(id) ON DELETE SET NULL,CONSTRAINT fk_session_rate FOREIGN KEY(rate_plan_id) REFERENCES rate_plans(id) ON DELETE SET NULL) ENGINE=InnoDB;
-- The loyalty table must be created after sessions because it has a foreign key to sessions(id).
CREATE TABLE player_loyalty_log (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,player_id INT UNSIGNED NOT NULL,session_id INT UNSIGNED NULL,points_change INT NOT NULL,reason VARCHAR(255) NOT NULL,balance_after INT NOT NULL,created_by INT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY idx_loyalty_player(player_id,created_at),CONSTRAINT fk_loyalty_player FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE,CONSTRAINT fk_loyalty_session FOREIGN KEY(session_id) REFERENCES sessions(id) ON DELETE SET NULL,CONSTRAINT fk_loyalty_user FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE session_frames (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,session_id INT UNSIGNED NOT NULL,frame_number INT NOT NULL,winner_player VARCHAR(120),duration_seconds INT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY idx_frame_session(session_id),CONSTRAINT fk_frame_session FOREIGN KEY(session_id) REFERENCES sessions(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE held_bills (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,club_id INT UNSIGNED NOT NULL,session_id INT UNSIGNED NOT NULL,player_id INT UNSIGNED NULL,amount DECIMAL(12,2) NOT NULL,notes TEXT,held_at DATETIME NOT NULL,settled_at DATETIME NULL,settled_by INT UNSIGNED NULL,status ENUM('held','settled','cancelled') NOT NULL DEFAULT 'held',KEY idx_held_club_status(club_id,status),CONSTRAINT fk_held_club FOREIGN KEY(club_id) REFERENCES clubs(id) ON DELETE CASCADE,CONSTRAINT fk_held_session FOREIGN KEY(session_id) REFERENCES sessions(id) ON DELETE CASCADE,CONSTRAINT fk_held_player FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE SET NULL,CONSTRAINT fk_held_user FOREIGN KEY(settled_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE cafe_items (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,club_id INT UNSIGNED NOT NULL,name VARCHAR(120) NOT NULL,category VARCHAR(80) NOT NULL DEFAULT 'Other',price DECIMAL(10,2) NOT NULL,stock_quantity INT NOT NULL DEFAULT 0,low_stock_threshold INT NOT NULL DEFAULT 0,is_available TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_cafe_club_available(club_id,is_available),CONSTRAINT fk_cafe_club FOREIGN KEY(club_id) REFERENCES clubs(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE cafe_orders (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,session_id INT UNSIGNED NULL,club_id INT UNSIGNED NOT NULL,player_id INT UNSIGNED NULL,operator_id INT UNSIGNED NOT NULL,is_standalone TINYINT(1) NOT NULL DEFAULT 0,total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,payment_method VARCHAR(30) NULL,status ENUM('open','completed','cancelled') NOT NULL DEFAULT 'open',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY idx_cafe_order_session(session_id),KEY idx_cafe_order_club(club_id),CONSTRAINT fk_order_session FOREIGN KEY(session_id) REFERENCES sessions(id) ON DELETE SET NULL,CONSTRAINT fk_order_club FOREIGN KEY(club_id) REFERENCES clubs(id) ON DELETE CASCADE,CONSTRAINT fk_order_player FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE SET NULL,CONSTRAINT fk_order_user FOREIGN KEY(operator_id) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE cafe_order_items (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id INT UNSIGNED NOT NULL,cafe_item_id INT UNSIGNED NULL,item_name VARCHAR(120) NOT NULL,item_price DECIMAL(10,2) NOT NULL,quantity INT NOT NULL,subtotal DECIMAL(12,2) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY idx_order_item_order(order_id),CONSTRAINT fk_order_item_order FOREIGN KEY(order_id) REFERENCES cafe_orders(id) ON DELETE CASCADE,CONSTRAINT fk_order_item_cafe FOREIGN KEY(cafe_item_id) REFERENCES cafe_items(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE expenses (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,club_id INT UNSIGNED NOT NULL,category ENUM('electricity','rent','water','salaries','equipment','maintenance','miscellaneous') NOT NULL,amount DECIMAL(12,2) NOT NULL,description TEXT,expense_date DATE NOT NULL,receipt_note VARCHAR(255),added_by INT UNSIGNED NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_expense_club_date(club_id,expense_date),CONSTRAINT fk_expense_club FOREIGN KEY(club_id) REFERENCES clubs(id) ON DELETE CASCADE,CONSTRAINT fk_expense_user FOREIGN KEY(added_by) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE inventory_items (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,club_id INT UNSIGNED NOT NULL,name VARCHAR(120) NOT NULL,category ENUM('cafe_stock','equipment') NOT NULL,current_stock DECIMAL(12,2) NOT NULL DEFAULT 0,unit VARCHAR(30) NOT NULL DEFAULT 'units',low_stock_threshold DECIMAL(12,2) NOT NULL DEFAULT 0,cost_per_unit DECIMAL(12,2) NOT NULL DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_inventory_club(club_id),CONSTRAINT fk_inventory_club FOREIGN KEY(club_id) REFERENCES clubs(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE inventory_log (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,inventory_item_id INT UNSIGNED NOT NULL,change_quantity DECIMAL(12,2) NOT NULL,change_type ENUM('purchase','sale','adjustment','damage') NOT NULL,vendor_name VARCHAR(120),cost DECIMAL(12,2),notes TEXT,created_by INT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY idx_inventory_log_item(inventory_item_id),CONSTRAINT fk_inventory_log_item FOREIGN KEY(inventory_item_id) REFERENCES inventory_items(id) ON DELETE CASCADE,CONSTRAINT fk_inventory_log_user FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE tournaments (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,club_id INT UNSIGNED NOT NULL,name VARCHAR(150) NOT NULL,sport ENUM('snooker','8ball','9ball') NOT NULL,format ENUM('single_elim','double_elim','round_robin') NOT NULL,match_format ENUM('best_of','race_to') NOT NULL,frames_count INT NOT NULL,entry_fee DECIMAL(12,2) NOT NULL DEFAULT 0,prize_pool DECIMAL(12,2) NOT NULL DEFAULT 0,prize_breakdown JSON NULL,status ENUM('draft','registration','active','completed') NOT NULL DEFAULT 'draft',template_name VARCHAR(120),created_by INT UNSIGNED NOT NULL,started_at DATETIME NULL,completed_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY idx_tournament_club(club_id,status),CONSTRAINT fk_tournament_club FOREIGN KEY(club_id) REFERENCES clubs(id) ON DELETE CASCADE,CONSTRAINT fk_tournament_user FOREIGN KEY(created_by) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE tournament_players (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,tournament_id INT UNSIGNED NOT NULL,player_id INT UNSIGNED NULL,player_name VARCHAR(120) NOT NULL,seed_number INT NULL,entry_fee_paid TINYINT(1) NOT NULL DEFAULT 0,status ENUM('registered','active','eliminated') NOT NULL DEFAULT 'registered',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY idx_tournament_player(tournament_id),CONSTRAINT fk_tournament_player_t FOREIGN KEY(tournament_id) REFERENCES tournaments(id) ON DELETE CASCADE,CONSTRAINT fk_tournament_player_p FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE tournament_matches (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,tournament_id INT UNSIGNED NOT NULL,round_number INT NOT NULL,match_number INT NOT NULL,player1_id INT UNSIGNED NULL,player2_id INT UNSIGNED NULL,player1_name VARCHAR(120),player2_name VARCHAR(120),player1_frames INT NOT NULL DEFAULT 0,player2_frames INT NOT NULL DEFAULT 0,winner_id INT UNSIGNED NULL,winner_name VARCHAR(120),session_id INT UNSIGNED NULL,table_id INT UNSIGNED NULL,status ENUM('pending','running','completed') NOT NULL DEFAULT 'pending',played_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY idx_match_tournament(tournament_id,round_number),CONSTRAINT fk_match_tournament FOREIGN KEY(tournament_id) REFERENCES tournaments(id) ON DELETE CASCADE,CONSTRAINT fk_match_p1 FOREIGN KEY(player1_id) REFERENCES tournament_players(id) ON DELETE SET NULL,CONSTRAINT fk_match_p2 FOREIGN KEY(player2_id) REFERENCES tournament_players(id) ON DELETE SET NULL,CONSTRAINT fk_match_winner FOREIGN KEY(winner_id) REFERENCES tournament_players(id) ON DELETE SET NULL,CONSTRAINT fk_match_session FOREIGN KEY(session_id) REFERENCES sessions(id) ON DELETE SET NULL,CONSTRAINT fk_match_table FOREIGN KEY(table_id) REFERENCES tables(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE leaderboard_entries (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,club_id INT UNSIGNED NOT NULL,player_id INT UNSIGNED NOT NULL,rank_position INT NOT NULL,category VARCHAR(50) NOT NULL,period ENUM('daily','weekly','monthly','alltime') NOT NULL,value DECIMAL(12,2) NOT NULL DEFAULT 0,is_manual TINYINT(1) NOT NULL DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_leaderboard(club_id,player_id,category,period),CONSTRAINT fk_leader_club FOREIGN KEY(club_id) REFERENCES clubs(id) ON DELETE CASCADE,CONSTRAINT fk_leader_player FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE settings (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,club_id INT UNSIGNED NOT NULL,setting_key VARCHAR(100) NOT NULL,setting_value TEXT,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_setting(club_id,setting_key),CONSTRAINT fk_setting_club FOREIGN KEY(club_id) REFERENCES clubs(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE audit_log (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,club_id INT UNSIGNED NULL,user_id INT UNSIGNED NULL,action VARCHAR(100) NOT NULL,entity_type VARCHAR(100) NOT NULL,entity_id INT UNSIGNED NULL,old_value JSON NULL,new_value JSON NULL,ip_address VARCHAR(45),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY idx_audit_club_created(club_id,created_at),CONSTRAINT fk_audit_club FOREIGN KEY(club_id) REFERENCES clubs(id) ON DELETE SET NULL,CONSTRAINT fk_audit_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE notifications (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,club_id INT UNSIGNED NOT NULL,type VARCHAR(50) NOT NULL,message VARCHAR(255) NOT NULL,is_read TINYINT(1) NOT NULL DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY idx_notice_club_read(club_id,is_read),CONSTRAINT fk_notice_club FOREIGN KEY(club_id) REFERENCES clubs(id) ON DELETE CASCADE) ENGINE=InnoDB;
SET FOREIGN_KEY_CHECKS=1;


-- Demonstration data
SET NAMES utf8mb4;
START TRANSACTION;
INSERT INTO clubs (id,name,address,phone,tv_token,loyalty_points_rate,loyalty_redemption_rate,currency_symbol) VALUES (1,'Royal Snooker Club','Main Boulevard, Gulberg, Lahore','0300-1234567','4bfc5ee2e9974c0bba91ba7d048fa9f2',10,1,'Rs.');
INSERT INTO users (id,club_id,name,email,password,role,is_active) VALUES
(1,1,'Hassan Ahmed','admin@demo.com','$2y$10$C2.ORv8C/vsezZphA0KEP.KbdOaLNq/8iXJjktbM8nwY6EPm7GS2S','owner',1),
(2,1,'Ayesha Malik','manager@demo.com','$2y$10$C2.ORv8C/vsezZphA0KEP.KbdOaLNq/8iXJjktbM8nwY6EPm7GS2S','manager',1),
(3,1,'Muhammad Ali','cashier1@demo.com','$2y$10$C2.ORv8C/vsezZphA0KEP.KbdOaLNq/8iXJjktbM8nwY6EPm7GS2S','cashier',1),
(4,1,'Usman Raza','cashier2@demo.com','$2y$10$C2.ORv8C/vsezZphA0KEP.KbdOaLNq/8iXJjktbM8nwY6EPm7GS2S','cashier',1);
INSERT INTO rate_plans (id,club_id,plan_name,billing_type,rate_per_minute,rate_per_frame,slab_config) VALUES
(1,1,'Standard','per_minute',10,0,NULL),(2,1,'Premium','per_minute',15,0,NULL),(3,1,'Weekend Slab','slab',0,0,'[{"up_to_minutes":15,"price":200},{"up_to_minutes":60,"price":700},{"per_extra_minutes":15,"extra_price":100}]'),(4,1,'Frame Match','per_frame',0,180,NULL);
INSERT INTO tables (id,club_id,table_number,table_name,table_type,status,rate_plan_id) VALUES
(1,1,'1','Table 1','snooker','available',1),(2,1,'2','Table 2','snooker','available',1),(3,1,'3','Table 3','snooker','available',2),(4,1,'4','Table 4','snooker','available',2),(5,1,'5','Table 5','snooker','available',1),(6,1,'6','Table 6','snooker','available',3),(7,1,'7','Pool Table 1','pool','available',1),(8,1,'8','Pool Table 2','pool','available',4);
INSERT INTO players (id,club_id,name,phone,email,tier,loyalty_points,total_spent,total_visits,ledger_balance,joined_date,last_visit) VALUES
(1,1,'Ahmed Khan','0301-1111111','ahmed@example.com','gold',1840,18400,20,0,'2025-10-14',NOW()-INTERVAL 1 DAY),(2,1,'Bilal Shah','0302-2222222','bilal@example.com','silver',720,7200,11,0,'2025-12-05',NOW()-INTERVAL 2 DAY),(3,1,'Hamza Iqbal','0303-3333333','hamza@example.com','regular',210,2100,5,0,'2026-01-08',NOW()-INTERVAL 3 DAY),(4,1,'Ali Raza','0304-4444444','ali@example.com','platinum',5300,53000,42,0,'2025-06-12',NOW()-INTERVAL 5 DAY),(5,1,'Zain Abbas','0305-5555555','zain@example.com','gold',1630,16300,18,-450,'2025-08-02',NOW()-INTERVAL 6 DAY),(6,1,'Saad Ahmed','0306-6666666','saad@example.com','silver',650,6500,12,0,'2025-11-18',NOW()-INTERVAL 7 DAY),(7,1,'Danish Rauf','0307-7777777','danish@example.com','regular',300,3000,8,0,'2026-02-02',NOW()-INTERVAL 9 DAY),(8,1,'Fahad Qureshi','0308-8888888','fahad@example.com','gold',1770,17700,21,0,'2025-07-19',NOW()-INTERVAL 10 DAY),(9,1,'Usman Khalid','0309-9999999','usman@example.com','silver',820,8200,10,0,'2025-10-28',NOW()-INTERVAL 12 DAY),(10,1,'Taimur Javed','0310-1010101','taimur@example.com','regular',120,1200,3,0,'2026-03-01',NOW()-INTERVAL 14 DAY),(11,1,'Salman Akram','0311-1111111','salman@example.com','gold',1900,19000,26,0,'2025-07-01',NOW()-INTERVAL 16 DAY),(12,1,'Noman Tariq','0312-1212121','noman@example.com','regular',80,800,2,0,'2026-04-04',NOW()-INTERVAL 17 DAY),(13,1,'Ibrahim Zafar','0313-1313131','ibrahim@example.com','silver',930,9300,13,0,'2025-12-21',NOW()-INTERVAL 20 DAY),(14,1,'Talha Awan','0314-1414141','talha@example.com','regular',430,4300,7,0,'2026-01-31',NOW()-INTERVAL 21 DAY),(15,1,'Rayan Siddiq','0315-1515151','rayan@example.com','platinum',6200,62000,47,0,'2025-04-09',NOW()-INTERVAL 25 DAY);
INSERT INTO cafe_items (id,club_id,name,category,price,stock_quantity,low_stock_threshold) VALUES
(1,1,'Karak Chai','Drinks',30,80,10),(2,1,'Cold Drink','Drinks',80,50,8),(3,1,'Mineral Water','Drinks',50,65,10),(4,1,'Fresh Juice','Drinks',120,35,5),(5,1,'Samosa','Food',65,45,8),(6,1,'Club Sandwich','Food',220,25,5),(7,1,'French Fries','Food',180,32,5),(8,1,'Chips','Food',70,40,6),(9,1,'Chocolate','Other',100,30,5),(10,1,'Cue Chalk','Accessories',40,20,4);
INSERT INTO inventory_items (club_id,name,category,current_stock,unit,low_stock_threshold,cost_per_unit) VALUES
(1,'Chai Bags','cafe_stock',80,'bags',10,15),(1,'Cold Drink Bottles','cafe_stock',50,'bottles',8,55),(1,'Mineral Water','cafe_stock',65,'bottles',10,30),(1,'Snooker Chalk','equipment',2,'pieces',5,25),(1,'Cue Tips','equipment',5,'pieces',8,120),(1,'Cue Sticks','equipment',12,'pieces',3,1800);
INSERT INTO sessions (club_id,table_id,player_id,operator_id,start_time,end_time,total_pause_seconds,billing_type,rate_plan_id,frames_played,table_amount,cafe_amount,total_amount,discount_amount,points_used,points_earned,payment_method,status) VALUES
(1,1,1,3,NOW()-INTERVAL 1 DAY-INTERVAL 95 MINUTE,NOW()-INTERVAL 1 DAY,0,'per_minute',1,0,950,130,973,107,0,97,'cash','completed'),
(1,2,2,3,NOW()-INTERVAL 2 DAY-INTERVAL 60 MINUTE,NOW()-INTERVAL 2 DAY,0,'per_minute',1,0,600,80,646,34,0,64,'jazzcash','completed'),
(1,3,3,4,NOW()-INTERVAL 3 DAY-INTERVAL 83 MINUTE,NOW()-INTERVAL 3 DAY,0,'per_minute',2,0,1245,0,1245,0,0,124,'cash','completed'),
(1,4,4,3,NOW()-INTERVAL 4 DAY-INTERVAL 75 MINUTE,NOW()-INTERVAL 4 DAY,0,'per_minute',2,0,1125,220,1211,134,0,121,'cash','completed'),
(1,5,5,4,NOW()-INTERVAL 5 DAY-INTERVAL 45 MINUTE,NOW()-INTERVAL 5 DAY,0,'per_minute',1,0,450,180,567,63,0,56,'easypaisa','completed'),
(1,6,6,3,NOW()-INTERVAL 6 DAY-INTERVAL 75 MINUTE,NOW()-INTERVAL 6 DAY,0,'slab',3,0,800,0,760,40,0,76,'cash','completed'),
(1,7,7,4,NOW()-INTERVAL 7 DAY-INTERVAL 50 MINUTE,NOW()-INTERVAL 7 DAY,0,'per_minute',1,0,500,100,600,0,0,60,'cash','completed'),
(1,8,8,3,NOW()-INTERVAL 8 DAY-INTERVAL 3 HOUR,NOW()-INTERVAL 8 DAY,0,'per_frame',4,4,720,120,756,84,0,75,'jazzcash','completed'),
(1,1,9,4,NOW()-INTERVAL 9 DAY-INTERVAL 70 MINUTE,NOW()-INTERVAL 9 DAY,0,'per_minute',1,0,700,65,727,38,0,72,'cash','completed'),
(1,2,10,3,NOW()-INTERVAL 11 DAY-INTERVAL 48 MINUTE,NOW()-INTERVAL 11 DAY,0,'per_minute',1,0,480,0,480,0,0,48,'cash','completed'),
(1,3,11,4,NOW()-INTERVAL 13 DAY-INTERVAL 88 MINUTE,NOW()-INTERVAL 13 DAY,0,'per_minute',2,0,1320,80,1260,140,0,126,'easypaisa','completed'),
(1,4,12,3,NOW()-INTERVAL 15 DAY-INTERVAL 30 MINUTE,NOW()-INTERVAL 15 DAY,0,'per_minute',2,0,450,30,480,0,0,48,'cash','completed'),
(1,5,13,4,NOW()-INTERVAL 18 DAY-INTERVAL 90 MINUTE,NOW()-INTERVAL 18 DAY,0,'per_minute',1,0,900,120,969,51,0,96,'jazzcash','completed'),
(1,6,14,3,NOW()-INTERVAL 19 DAY-INTERVAL 60 MINUTE,NOW()-INTERVAL 19 DAY,0,'slab',3,0,700,0,700,0,0,70,'cash','completed'),
(1,7,15,4,NOW()-INTERVAL 22 DAY-INTERVAL 40 MINUTE,NOW()-INTERVAL 22 DAY,0,'per_minute',1,0,400,100,425,75,0,42,'cash','completed'),
(1,8,1,3,NOW()-INTERVAL 23 DAY-INTERVAL 2 HOUR,NOW()-INTERVAL 23 DAY,0,'per_frame',4,3,540,60,540,60,0,54,'easypaisa','completed'),
(1,1,2,4,NOW()-INTERVAL 24 DAY-INTERVAL 55 MINUTE,NOW()-INTERVAL 24 DAY,0,'per_minute',1,0,550,0,523,27,0,52,'cash','completed'),
(1,2,4,3,NOW()-INTERVAL 26 DAY-INTERVAL 100 MINUTE,NOW()-INTERVAL 26 DAY,0,'per_minute',1,0,1000,220,1098,122,0,109,'jazzcash','completed'),
(1,3,5,4,NOW()-INTERVAL 28 DAY-INTERVAL 72 MINUTE,NOW()-INTERVAL 28 DAY,0,'per_minute',2,0,1080,130,1089,121,0,108,'cash','completed'),
(1,4,6,3,NOW()-INTERVAL 29 DAY-INTERVAL 62 MINUTE,NOW()-INTERVAL 29 DAY,0,'per_minute',2,0,930,60,943,47,0,94,'cash','completed');
INSERT INTO cafe_orders (session_id,club_id,player_id,operator_id,total_amount,payment_method,status) SELECT id,club_id,player_id,operator_id,cafe_amount,payment_method,'completed' FROM sessions WHERE cafe_amount>0;
INSERT INTO expenses (club_id,category,amount,description,expense_date,added_by) VALUES
(1,'electricity',5000,'Monthly electricity bill',CURDATE()-INTERVAL 3 DAY,1),(1,'rent',25000,'Club rent',DATE_FORMAT(CURDATE(),'%Y-%m-01'),1),(1,'water',1200,'Water supply',CURDATE()-INTERVAL 8 DAY,2),(1,'maintenance',3500,'Table cloth repair',CURDATE()-INTERVAL 15 DAY,2),(1,'salaries',12000,'Staff advance',CURDATE()-INTERVAL 20 DAY,1);
INSERT INTO tournaments (id,club_id,name,sport,format,match_format,frames_count,entry_fee,prize_pool,prize_breakdown,status,created_by,started_at,completed_at) VALUES (1,1,'Lahore Weekend Championship','snooker','single_elim','best_of',5,500,8000,'{"first":5000,"second":2000,"third":1000}','completed',1,NOW()-INTERVAL 45 DAY,NOW()-INTERVAL 43 DAY);
INSERT INTO tournament_players (id,tournament_id,player_id,player_name,seed_number,entry_fee_paid,status) VALUES (1,1,1,'Ahmed Khan',1,1,'active'),(2,1,2,'Bilal Shah',2,1,'eliminated'),(3,1,4,'Ali Raza',3,1,'eliminated'),(4,1,5,'Zain Abbas',4,1,'eliminated');
INSERT INTO tournament_matches (tournament_id,round_number,match_number,player1_id,player2_id,player1_name,player2_name,player1_frames,player2_frames,winner_id,winner_name,status,played_at) VALUES (1,1,1,1,2,'Ahmed Khan','Bilal Shah',3,1,1,'Ahmed Khan','completed',NOW()-INTERVAL 44 DAY),(1,1,2,3,4,'Ali Raza','Zain Abbas',3,2,3,'Ali Raza','completed',NOW()-INTERVAL 44 DAY),(1,2,1,1,3,'Ahmed Khan','Ali Raza',3,2,1,'Ahmed Khan','completed',NOW()-INTERVAL 43 DAY);
INSERT INTO settings (club_id,setting_key,setting_value) VALUES (1,'tier_silver','500'),(1,'tier_gold','1500'),(1,'tier_platinum','5000'),(1,'tv_leaderboard_period','weekly');
INSERT INTO notifications (club_id,type,message) VALUES (1,'low_stock','Snooker Chalk is running low (2 pieces left).'),(1,'tier','Ahmed Khan upgraded to Gold tier!');
COMMIT;


-- SaaS extension with Pakistan per-table pricing
-- CuePOS SaaS extension. Run once on an existing CuePOS database after install/schema.sql.
ALTER TABLE clubs ADD COLUMN slug VARCHAR(120) NULL AFTER name, ADD COLUMN country_code CHAR(2) NULL AFTER phone, ADD COLUMN timezone VARCHAR(64) NOT NULL DEFAULT 'UTC' AFTER country_code, ADD COLUMN locale VARCHAR(12) NOT NULL DEFAULT 'en' AFTER timezone, ADD COLUMN currency_code CHAR(3) NOT NULL DEFAULT 'USD' AFTER locale, ADD COLUMN tenant_status ENUM('trial','active','past_due','suspended','cancelled') NOT NULL DEFAULT 'active' AFTER currency_symbol, ADD COLUMN trial_ends_at DATETIME NULL AFTER tenant_status, ADD COLUMN onboarding_completed_at DATETIME NULL AFTER trial_ends_at, ADD UNIQUE KEY uq_club_slug(slug), ADD KEY idx_clubs_status(tenant_status);
ALTER TABLE users ADD COLUMN is_platform_admin TINYINT(1) NOT NULL DEFAULT 0 AFTER is_active, ADD KEY idx_users_platform_admin(is_platform_admin);
CREATE TABLE plans (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,slug VARCHAR(50) NOT NULL UNIQUE,name VARCHAR(100) NOT NULL,tagline VARCHAR(150),description TEXT,price_monthly DECIMAL(12,2) NOT NULL DEFAULT 0,price_yearly DECIMAL(12,2) NOT NULL DEFAULT 0,currency_code CHAR(3) NOT NULL DEFAULT 'USD',table_limit INT NOT NULL DEFAULT 5,staff_limit INT NOT NULL DEFAULT 3,feature_flags JSON NULL,is_public TINYINT(1) NOT NULL DEFAULT 1,sort_order INT NOT NULL DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE subscriptions (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,club_id INT UNSIGNED NOT NULL,plan_id INT UNSIGNED NOT NULL,status ENUM('trial','active','past_due','cancelled','expired') NOT NULL DEFAULT 'trial',billing_interval ENUM('monthly','yearly') NOT NULL DEFAULT 'monthly',provider VARCHAR(50) NULL,provider_customer_id VARCHAR(191) NULL,provider_subscription_id VARCHAR(191) NULL,trial_ends_at DATETIME NULL,current_period_ends_at DATETIME NULL,starts_at DATETIME NOT NULL,ended_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_subscription_club_status(club_id,status),CONSTRAINT fk_subscription_club FOREIGN KEY(club_id) REFERENCES clubs(id) ON DELETE CASCADE,CONSTRAINT fk_subscription_plan FOREIGN KEY(plan_id) REFERENCES plans(id)) ENGINE=InnoDB;
CREATE TABLE club_memberships (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,club_id INT UNSIGNED NOT NULL,user_id INT UNSIGNED NOT NULL,membership_role ENUM('owner','manager','cashier','operator') NOT NULL DEFAULT 'operator',status ENUM('invited','active','disabled') NOT NULL DEFAULT 'active',joined_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_club_member(club_id,user_id),KEY idx_membership_user(user_id,status),CONSTRAINT fk_membership_club FOREIGN KEY(club_id) REFERENCES clubs(id) ON DELETE CASCADE,CONSTRAINT fk_membership_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE trial_signups (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,club_id INT UNSIGNED NOT NULL,owner_user_id INT UNSIGNED NOT NULL,email VARCHAR(190) NOT NULL,plan_id INT UNSIGNED NOT NULL,source VARCHAR(100) NULL,ip_address VARCHAR(45) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY idx_trial_email(email),CONSTRAINT fk_trial_club FOREIGN KEY(club_id) REFERENCES clubs(id) ON DELETE CASCADE,CONSTRAINT fk_trial_user FOREIGN KEY(owner_user_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT fk_trial_plan FOREIGN KEY(plan_id) REFERENCES plans(id)) ENGINE=InnoDB;
CREATE TABLE demo_requests (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(190) NOT NULL,club_name VARCHAR(150) NOT NULL,country_code CHAR(2) NULL,message TEXT,status ENUM('new','contacted','qualified','closed') NOT NULL DEFAULT 'new',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_demo_status_created(status,created_at)) ENGINE=InnoDB;
CREATE TABLE platform_settings (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,setting_key VARCHAR(100) NOT NULL UNIQUE,setting_value TEXT,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB;
INSERT INTO plans(slug,name,tagline,description,price_monthly,price_yearly,currency_code,table_limit,staff_limit,feature_flags,is_public,sort_order) VALUES ('free','Free Plan','Start with one table','One table, basic billing and a simple way to experience CuePOS in your club.',0,0,'PKR',1,1,JSON_OBJECT('basic_billing',true,'cafe',false,'reports',false,'tournaments',false),1,1),('pro','Pro Plan','Pay per table as your club grows','Rs. 449 per table per month for up to 10 tables.',449,0,'PKR',10,10,JSON_OBJECT('basic_billing',true,'cafe',false,'reports',false,'tournaments',false,'per_table_billing',true,'rate_per_table',449,'tier_breakpoint',10),1,2),('premium','Premium Plan','For clubs with more than 10 tables','Rs. 400 per table per month for clubs with more than 10 tables, with café operations, reports and full club management.',400,0,'PKR',9999,25,JSON_OBJECT('basic_billing',true,'cafe',true,'reports',true,'tournaments',true,'unlimited_tables',true,'per_table_billing',true,'rate_per_table',400,'minimum_tables',11),1,3);
INSERT INTO subscriptions(club_id,plan_id,status,billing_interval,starts_at) SELECT c.id,(SELECT id FROM plans WHERE slug='pro'),'active','monthly',NOW() FROM clubs c WHERE NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.club_id=c.id);
INSERT INTO club_memberships(club_id,user_id,membership_role,status,joined_at) SELECT u.club_id,u.id,u.role,'active',NOW() FROM users u WHERE NOT EXISTS (SELECT 1 FROM club_memberships m WHERE m.club_id=u.club_id AND m.user_id=u.id);
UPDATE clubs SET slug=CONCAT('club-',id) WHERE slug IS NULL OR slug='';
UPDATE users SET is_platform_admin=1 WHERE email='admin@demo.com';
