-- CuePOS SaaS extension. Run once on an existing CuePOS database after install/schema.sql.
ALTER TABLE clubs ADD COLUMN slug VARCHAR(120) NULL AFTER name, ADD COLUMN country_code CHAR(2) NULL AFTER phone, ADD COLUMN timezone VARCHAR(64) NOT NULL DEFAULT 'UTC' AFTER country_code, ADD COLUMN locale VARCHAR(12) NOT NULL DEFAULT 'en' AFTER timezone, ADD COLUMN currency_code CHAR(3) NOT NULL DEFAULT 'USD' AFTER locale, ADD COLUMN tenant_status ENUM('trial','active','past_due','suspended','cancelled') NOT NULL DEFAULT 'active' AFTER currency_symbol, ADD COLUMN trial_ends_at DATETIME NULL AFTER tenant_status, ADD COLUMN onboarding_completed_at DATETIME NULL AFTER trial_ends_at, ADD UNIQUE KEY uq_club_slug(slug), ADD KEY idx_clubs_status(tenant_status);
ALTER TABLE users ADD COLUMN is_platform_admin TINYINT(1) NOT NULL DEFAULT 0 AFTER is_active, ADD KEY idx_users_platform_admin(is_platform_admin);
CREATE TABLE plans (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,slug VARCHAR(50) NOT NULL UNIQUE,name VARCHAR(100) NOT NULL,tagline VARCHAR(150),description TEXT,price_monthly DECIMAL(12,2) NOT NULL DEFAULT 0,price_yearly DECIMAL(12,2) NOT NULL DEFAULT 0,currency_code CHAR(3) NOT NULL DEFAULT 'USD',table_limit INT NOT NULL DEFAULT 5,staff_limit INT NOT NULL DEFAULT 3,feature_flags JSON NULL,is_public TINYINT(1) NOT NULL DEFAULT 1,sort_order INT NOT NULL DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE subscriptions (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,club_id INT UNSIGNED NOT NULL,plan_id INT UNSIGNED NOT NULL,status ENUM('trial','active','past_due','cancelled','expired') NOT NULL DEFAULT 'trial',billing_interval ENUM('monthly','yearly') NOT NULL DEFAULT 'monthly',provider VARCHAR(50) NULL,provider_customer_id VARCHAR(191) NULL,provider_subscription_id VARCHAR(191) NULL,trial_ends_at DATETIME NULL,current_period_ends_at DATETIME NULL,starts_at DATETIME NOT NULL,ended_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_subscription_club_status(club_id,status),CONSTRAINT fk_subscription_club FOREIGN KEY(club_id) REFERENCES clubs(id) ON DELETE CASCADE,CONSTRAINT fk_subscription_plan FOREIGN KEY(plan_id) REFERENCES plans(id)) ENGINE=InnoDB;
CREATE TABLE club_memberships (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,club_id INT UNSIGNED NOT NULL,user_id INT UNSIGNED NOT NULL,membership_role ENUM('owner','manager','cashier','operator') NOT NULL DEFAULT 'operator',status ENUM('invited','active','disabled') NOT NULL DEFAULT 'active',joined_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_club_member(club_id,user_id),KEY idx_membership_user(user_id,status),CONSTRAINT fk_membership_club FOREIGN KEY(club_id) REFERENCES clubs(id) ON DELETE CASCADE,CONSTRAINT fk_membership_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE trial_signups (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,club_id INT UNSIGNED NOT NULL,owner_user_id INT UNSIGNED NOT NULL,email VARCHAR(190) NOT NULL,plan_id INT UNSIGNED NOT NULL,source VARCHAR(100) NULL,ip_address VARCHAR(45) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY idx_trial_email(email),CONSTRAINT fk_trial_club FOREIGN KEY(club_id) REFERENCES clubs(id) ON DELETE CASCADE,CONSTRAINT fk_trial_user FOREIGN KEY(owner_user_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT fk_trial_plan FOREIGN KEY(plan_id) REFERENCES plans(id)) ENGINE=InnoDB;
CREATE TABLE demo_requests (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(190) NOT NULL,club_name VARCHAR(150) NOT NULL,country_code CHAR(2) NULL,message TEXT,status ENUM('new','contacted','qualified','closed') NOT NULL DEFAULT 'new',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_demo_status_created(status,created_at)) ENGINE=InnoDB;
CREATE TABLE platform_settings (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,setting_key VARCHAR(100) NOT NULL UNIQUE,setting_value TEXT,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB;
INSERT INTO plans(slug,name,tagline,description,price_monthly,price_yearly,currency_code,table_limit,staff_limit,feature_flags,is_public,sort_order) VALUES ('free','Free Plan','Start with one table','One table, basic billing and a simple way to experience CuePOS in your club.',0,0,'PKR',1,1,JSON_OBJECT('basic_billing',true,'cafe',false,'reports',false,'tournaments',false),1,1),('pro','Pro Plan','Pay per table as your club grows','Rs. 449 per table per month for up to 10 tables.',449,0,'PKR',10,10,JSON_OBJECT('basic_billing',true,'cafe',false,'reports',false,'tournaments',false,'per_table_billing',true,'rate_per_table',449,'tier_breakpoint',10),1,2),('premium','Premium Plan','For clubs with more than 10 tables','Rs. 400 per table per month for clubs with more than 10 tables, with café operations, reports and full club management.',400,0,'PKR',9999,25,JSON_OBJECT('basic_billing',true,'cafe',true,'reports',true,'tournaments',true,'unlimited_tables',true,'per_table_billing',true,'rate_per_table',400,'minimum_tables',11),1,3);
INSERT INTO subscriptions(club_id,plan_id,status,billing_interval,starts_at) SELECT c.id,(SELECT id FROM plans WHERE slug='pro'),'active','monthly',NOW() FROM clubs c WHERE NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.club_id=c.id);
INSERT INTO club_memberships(club_id,user_id,membership_role,status,joined_at) SELECT u.club_id,u.id,u.role,'active',NOW() FROM users u WHERE NOT EXISTS (SELECT 1 FROM club_memberships m WHERE m.club_id=u.club_id AND m.user_id=u.id);
UPDATE clubs SET slug=CONCAT('club-',id) WHERE slug IS NULL OR slug='';
UPDATE users SET is_platform_admin=1 WHERE email='admin@demo.com';
