<?php
require_once __DIR__.'/bootstrap.php';
$publicTitle=$publicTitle ?? 'CuePOS | Snooker Club Management Software';
$publicDescription=$publicDescription ?? 'CuePOS is the all-in-one operating system for modern snooker clubs: live tables, POS, billing, players, café, reports and tournaments.';
$publicCanonical=$publicCanonical ?? siteUrl('/');
$publicKeywords=$publicKeywords ?? 'snooker club management software, snooker POS system, billiard club software, cue sports management';
$organizationSchema=['@context'=>'https://schema.org','@type'=>'Organization','name'=>'CuePOS','url'=>siteUrl('/'),'description'=>'Snooker club management software for table operations, POS, player loyalty, café sales and reporting.'];
$softwareSchema=['@context'=>'https://schema.org','@type'=>'SoftwareApplication','name'=>'CuePOS','applicationCategory'=>'BusinessApplication','operatingSystem'=>'Web','description'=>'Cloud software for snooker clubs to manage tables, billing, players, café sales, shifts and reporting.','url'=>siteUrl('/')];
$publicNav=[['features.php','Features'],['how-it-works.php','How it works'],['pricing.php','Pricing'],['snooker-club-software.php','For snooker clubs'],['faq.php','FAQ']];
?>
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=sanitize($publicTitle)?></title><meta name="description" content="<?=sanitize($publicDescription)?>"><meta name="keywords" content="<?=sanitize($publicKeywords)?>"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="<?=sanitize($publicCanonical)?>"><meta property="og:type" content="website"><meta property="og:title" content="<?=sanitize($publicTitle)?>"><meta property="og:description" content="<?=sanitize($publicDescription)?>"><meta property="og:url" content="<?=sanitize($publicCanonical)?>"><meta property="og:site_name" content="CuePOS"><meta name="twitter:card" content="summary_large_image"><?php if($verification=platformSetting('google_site_verification')): ?><meta name="google-site-verification" content="<?=sanitize($verification)?>"><?php endif; ?><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Outfit:wght@500;600;700;800&display=swap" rel="stylesheet"><script src="https://cdn.tailwindcss.com"></script><script>tailwind.config={theme:{extend:{fontFamily:{sans:['DM Sans','sans-serif'],display:['Outfit','sans-serif']},colors:{ink:'#071820',navy:'#0b2538',cue:'#10c779',lime:'#9df3ca',mist:'#edf7f3'}}}}</script><link rel="stylesheet" href="<?=url('assets/css/marketing.css')?>"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"><script type="application/ld+json"><?=json_encode($organizationSchema,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?></script><script type="application/ld+json"><?=json_encode($softwareSchema,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?></script></head>
<body class="bg-[#f7fbf9] text-ink font-sans"><header class="sticky top-0 z-50 border-b border-slate-200/80 bg-white/90 backdrop-blur-xl"><div class="max-w-7xl mx-auto px-5 flex h-[74px] items-center justify-between"><a href="<?=url('')?>" class="flex items-center gap-2.5 font-display text-[1.45rem] font-extrabold tracking-tight" aria-label="CuePOS home"><span class="w-9 h-9 grid place-items-center rounded-xl bg-cue text-ink shadow-sm"><i class="fa-solid fa-circle-dot"></i></span>CuePOS</a><nav class="hidden lg:flex items-center gap-1 text-sm font-bold text-slate-600"><?php foreach($publicNav as [$link,$label]): ?><a class="rounded-lg px-3 py-2 hover:bg-emerald-50 hover:text-emerald-800 transition" href="<?=url($link)?>"><?=$label?></a><?php endforeach; ?></nav><div class="hidden sm:flex items-center gap-3"><a href="<?=url('login.php')?>" class="text-sm font-bold text-slate-600 hover:text-ink">Log in</a><a href="<?=url('trial.php')?>" class="btn-public btn-public-primary py-2.5 px-4">Start free trial <i class="fa-solid fa-arrow-right"></i></a></div><details class="relative sm:hidden group"><summary class="list-none w-10 h-10 grid place-items-center rounded-xl border border-slate-200 text-slate-700 cursor-pointer"><i class="fa-solid fa-bars"></i></summary><div class="absolute right-0 mt-3 w-64 rounded-2xl bg-white border border-slate-200 p-2 shadow-2xl shadow-slate-900/15"><div class="px-3 py-2 text-[.68rem] font-extrabold uppercase tracking-[.13em] text-slate-400">Explore CuePOS</div><?php foreach($publicNav as [$link,$label]): ?><a class="block rounded-xl px-3 py-2.5 text-sm font-bold text-slate-700 hover:bg-emerald-50 hover:text-emerald-800" href="<?=url($link)?>"><?=$label?></a><?php endforeach; ?><div class="my-2 border-t border-slate-100"></div><a class="block rounded-xl px-3 py-2.5 text-sm font-bold text-slate-700 hover:bg-slate-50" href="<?=url('login.php')?>">Log in</a><a class="block rounded-xl bg-ink px-3 py-3 text-center text-sm font-bold text-white" href="<?=url('trial.php')?>">Start free trial</a></div></details></div></header>
